source 'https://rubygems.org'

gem 'rails', '>= 4.0'

gem 'sqlite3', :platforms => :ruby

platforms :jruby do
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbcsqlite3-adapter'
end

gem 'haml'

gem 'kaminari'

gem 'rspec-rails'

gem 'uglifier'       #, '>= 1.0.3'
gem 'sass-rails'
gem 'coffee-rails'
gem 'jquery-rails'

#gem 'bootstrap-sass-rails'
gem 'therubyracer', :require => RUBY_PLATFORM.include?('linux') && 'v8'

gem 'turbolinks'
gem 'jbuilder', '~> 1.2'

group :doc do
	gem 'sdoc', require: false
end