source 'http://rubygems.org'

gem 'rails', '>= 3.2'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3', :platforms => :ruby

platforms :jruby do 
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbcsqlite3-adapter'
end

gem 'json'

gem 'haml'

gem 'kaminari'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'     #, '~> 3.2.3'
  gem 'coffee-rails'   #, '~> 3.2.1'
  gem 'uglifier'       #, '>= 1.0.3'
  gem 'bootstrap-sass-rails'
  #gem 'therubyracer'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'
