source 'http://rubygems.org'

gem 'rails', github: 'rails/rails'
gem 'arel',  github: 'rails/arel'
gem 'activerecord-deprecated_finders', github: 'rails/activerecord-deprecated_finders'


gem 'sqlite3', :platforms => :ruby

platforms :jruby do
  gem 'jdbc-sqlite3'
  gem 'activerecord-jdbcsqlite3-adapter'
end

gem 'json'

gem 'sass'
gem 'haml'

gem 'kaminari'

gem 'rspec-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sprockets-rails', github: 'rails/sprockets-rails'
  gem 'sass-rails',      github: 'rails/sass-rails'
  gem 'coffee-rails',    github: 'rails/coffee-rails'

  gem 'uglifier'       #, '>= 1.0.3'
  #gem 'bootstrap-sass-rails'
  gem 'therubyracer', :require => RUBY_PLATFORM.include?('linux') && 'v8'
end

gem 'jquery-rails'
gem 'turbolinks'

